name: Build Kernel for Xiaomi MSM8937

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison flex build-essential libncurses5-dev libssl-dev ccache

    - name: Setup GCC
      run: |
        sudo apt-get install -y gcc-arm64 gcc-armhf
        export CROSS_COMPILE_ARM32=arm-linux-gnueabihf-
        export CROSS_COMPILE_ARM64=aarch64-linux-gnu-
        export ARCH=arm64

    - name: Build kernel
      run: |
        make O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig
        make -j$(nproc) O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-

    - name: Create flashable zip
      run: |
        mkdir -p anykernel
        git clone https://github.com/osm0sis/AnyKernel3.git anykernel/
        cp out/arch/arm64/boot/Image.gz-dtb anykernel/
        cd anykernel
        zip -r9 ../Flashable-Kernel.zip *

    - name: Upload to release
      uses: ncipollo/release-action@v1
      with:
        artifacts: Flashable-Kernel.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: Kernel Build ${{ github.ref_name }}
        body: |
          Flashable kernel built from `${{ github.repository }}` for device Xiaomi MSM8937
        draft: false
        prerelease: false
